### ISSUE TITLE
Error on Running  rails db:seed

### ISSUE THREAD

**Issue by anoobbava** [jayakrishnang/auction-manager-v2#16]
auction-manager-v2 master % rails db:seed
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
rails aborted!
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column users.password does not exist
LINE 1: ... "users"."name" = $1 AND "users"."email" = $2 AND "users"."p...
                                                             ^
: SELECT  "users".* FROM "users" WHERE "users"."name" = $1 AND "users"."email" = $2 AND "users"."password" = $3 AND "users"."password_confirmation" = $4 LIMIT $5
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:669:in `async_prepare'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:669:in `block in prepare_statement'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:664:in `prepare_statement'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:609:in `exec_cache'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `execute_and_clear'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:469:in `select_prepared'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:55:in `select_all'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `select_all'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/querying.rb:41:in `find_by_sql'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:554:in `block in exec_queries'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:578:in `skip_query_cache_if_necessary'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:541:in `exec_queries'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:414:in `load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:200:in `records'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation/finder_methods.rb:500:in `find_take'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation/finder_methods.rb:103:in `take'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation/finder_methods.rb:81:in `find_by'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:164:in `find_or_create_by'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/querying.rb:8:in `find_or_create_by'
/home/anoobbava/ror/auction-manager-v2/db/seeds.rb:5:in `<main>'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/engine.rb:551:in `load_seed'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <main>'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/command.rb:48:in `invoke'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
/home/anoobbava/ror/auction-manager-v2/bin/rails:9:in `<top (required)>'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/home/anoobbava/ror/auction-manager-v2/bin/spring:15:in `require'
/home/anoobbava/ror/auction-manager-v2/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
PG::UndefinedColumn: ERROR:  column users.password does not exist
LINE 1: ... "users"."name" = $1 AND "users"."email" = $2 AND "users"."p...
                                                             ^
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:669:in `async_prepare'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:669:in `block in prepare_statement'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:664:in `prepare_statement'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:609:in `exec_cache'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `execute_and_clear'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:469:in `select_prepared'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:55:in `select_all'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `select_all'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/querying.rb:41:in `find_by_sql'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:554:in `block in exec_queries'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:578:in `skip_query_cache_if_necessary'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:541:in `exec_queries'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:414:in `load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:200:in `records'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation/finder_methods.rb:500:in `find_take'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation/finder_methods.rb:103:in `take'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation/finder_methods.rb:81:in `find_by'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/relation.rb:164:in `find_or_create_by'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/querying.rb:8:in `find_or_create_by'
/home/anoobbava/ror/auction-manager-v2/db/seeds.rb:5:in `<main>'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/engine.rb:551:in `load_seed'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <main>'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/command.rb:48:in `invoke'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
/home/anoobbava/ror/auction-manager-v2/bin/rails:9:in `<top (required)>'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/home/anoobbava/ror/auction-manager-v2/vendor/bundle/ruby/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/home/anoobbava/ror/auction-manager-v2/bin/spring:15:in `require'
/home/anoobbava/ror/auction-manager-v2/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

**Comment by anoobbava** [comment]
the Possible solution is >> 
https://stackoverflow.com/questions/25497473/rails-4-1-devise-3-3-column-users-password-does-not-exist

**Comment by anoobbava** [comment]
Raised PR for this issue 
PR >> https://github.com/jayakrishnang/auction-manager-v2/pull/17
@jayakrishnang , Please check
